### ISSUE TITLE
opcodes relying on callValue opens playground without Value to send 

### ISSUE THREAD

**Issue by Akkii4** [smlxl/evm.codes#265] opened 2023-08-04 17:51 UTC
Opcodes likes : 31, 34, 47, F0, F5 when reproduced opens without any Value in playground until being refreshed or if opened in new tab as doing such updates the url link 

e.g. CREATE(F0) 
original link(doesn't work) : https://www.evm.codes/playground?callValue=9&unit=Wei&codeType=Mnemonic&code=%27z0q0f9q9f0y4%20FFmslk3%200x63FFFFFFFF6000526004601CF3jvMSTORE~13jjp%20%27~k%20z%2F%2F%20Createmnmccountgith%20ygeimnd%20v%5Cnqynoljj~pvCREATEm%20al%20codekvPUSH1j~0g%20wfpvvz%01fgjklmpqvyz~_

post refresh/new tab : https://www.evm.codes/playground?callValue=9&unit=Wei&codeType=Mnemonic&code=%27z0q0f9q9f0y4+FFmslk3+0x63FFFFFFFF6000526004601CF3jvMSTORE%7E13jjp+%27%7Ek+z%2F%2F+Createmnmccountgith+ygeimnd+v%5Cnqynoljj%7EpvCREATEm+al+codekvPUSH1j%7E0g+wfpvvz%01fgjklmpqvyz%7E_&fork=shanghai

**Comment by 2xic** [comment] 2024-01-19 18:32
Closing this as I'm not able to reproduce - feel free to reopen (and maybe add a note on the browser you are using) if you still have issues

**Closed by 2xic** 2024-01-19 18:32 UTC
Labels: bug
